name: "Ensure Files Changed"
description: "Ensure Files Changed"
author: "danieljimeneznz"

inputs:
  file-names:
    description: "An array of strings that represent the files that should be included in the PR."
    required: true
  token:
    description: "The GitHub token used to create an authenticated client."
    required: true

outputs:
  success:
    description: "The success of the validated files."

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "git-pull-request"
  color: "orange"
